# Generated by Django 5.0.1 on 2024-01-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_bookinstance_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookinstance",
            name="language",
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.language",
            ),
        ),
    ]
